### ISSUE TITLE
What license are the model packs under?

### ISSUE THREAD

**Issue by HeadClot** [TheGameCreators/FPS-Creator-Classic#155]
Hey got a bit of a question is there any license file for the various model packs?

Can these be used in other engines? (Unreal, Cry engine, etc.)

**Comment by SoulRepo** [comment]
I believe these have been given out entierly free without a license by the creators.
These models will probably not work in other engines without converting it(?)

**Comment by HeadClot** [comment]
Thank you @SoulRepo for this info. 👍
